# Generated by Django 3.1 on 2020-08-22 13:13

from django.db import migrations, models
import image_picker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('image_picker', '0002_auto_20200822_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='dir_path',
            field=models.CharField(max_length=255, unique=True, validators=[image_picker.validators.validate_path_exists, image_picker.validators.validate_is_dir]),
        ),
    ]
