# Generated by Django 3.1 on 2023-09-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_picker', '0003_auto_20200822_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='pinned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
