# Generated by Django 3.1 on 2023-11-26 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_picker', '0004_auto_20230923_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='image_picker.gallery')),
            ],
            options={
                'verbose_name': 'Favorite image',
                'verbose_name_plural': 'Favorite images',
                'db_table': 'favorite_image',
            },
        ),
    ]
