# Generated by Django 3.1 on 2024-03-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_picker', '0005_favoriteimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=255)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_picker.gallery')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_picker.image')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_picker.tag')),
            ],
            options={
                'db_table': 'image_tags',
                'unique_together': {('image', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(through='image_picker.ImageTag', to='image_picker.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('filename', 'gallery')},
        ),
    ]
