# Generated by Django 3.1 on 2024-03-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_picker', '0006_auto_20240319_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
